/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.models.Autor;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Maza
 */
public class ListarAutorView extends javax.swing.JInternalFrame {
     private DefaultTableModel modelo;
    /**
     * Creates new form ListarAutorView
     */
    public ListarAutorView() {
        initComponents();
        configurarTabla();
    }
    public void configurarTabla(){
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Nacionalidad");
        
        tblAutor.setModel(modelo);
        
    
    }
     public void cargarDatos(List<Autor> libros){
        modelo.setRowCount(0);
        
        for( Autor libro : libros){
            Object[] fila = {libro.getCedula(),
                libro.getNombre(),
                libro.getApellido(),
                libro.getNacionalidad(),
            };
            
            modelo.addRow(fila);
        }
    }

    public JButton getBtnCancelarA() {
        return btnCancelarA;
    }

    public void setBtnCancelarA(JButton btnCancelarA) {
        this.btnCancelarA = btnCancelarA;
    }

    public JButton getBtnListarAu() {
        return btnListarAu;
    }

    public void setBtnListarAu(JButton btnListarAu) {
        this.btnListarAu = btnListarAu;
    }
    public void cambiarIdioma(Locale locale){

    ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
            



    btnListarAu.setText(bundle.getString("listar"));
    btnCancelarA.setText(bundle.getString("cancelar"));

    tblAutor.getColumnModel().getColumn(0)
            .setHeaderValue(bundle.getString("cedula"));

    tblAutor.getColumnModel().getColumn(1)
            .setHeaderValue(bundle.getString("nombre"));

    tblAutor.getColumnModel().getColumn(2)
            .setHeaderValue(bundle.getString("apellido"));

    tblAutor.getColumnModel().getColumn(3)
            .setHeaderValue(bundle.getString("nacionalidad"));
    

    tblAutor.getTableHeader().repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnListarAu = new javax.swing.JButton();
        btnCancelarA = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutor);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnListarAu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnListarAu.setText("Listar");

        btnCancelarA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCancelarA.setText("Cancelar");
        btnCancelarA.addActionListener(this::btnCancelarAActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListarAu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnListarAu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAActionPerformed
          dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarA;
    private javax.swing.JButton btnListarAu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutor;
    // End of variables declaration//GEN-END:variables
}
