/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.controllers.AutorController;
import ec.edu.ups.biblioteca.controllers.LibroController;
import ec.edu.ups.biblioteca.controllers.UsuarioController;
import ec.edu.ups.biblioteca.dao.AutorDAO;
import ec.edu.ups.biblioteca.dao.AutorDAOMemoria;
import ec.edu.ups.biblioteca.dao.LibroDAO;
import ec.edu.ups.biblioteca.dao.LibroDAOMemoria;
import ec.edu.ups.biblioteca.dao.UsuarioDAO;
import ec.edu.ups.biblioteca.dao.UsuarioDAOMemoria;

/**
 *
 * @author Miguel Maza
 */
public class PrinicipalView extends javax.swing.JFrame {
    private RegistrarLibroView registrarLibroView;
    private BuscarLibroView buscarLibroView;
    private LibroDAO libroDAO;
    private LibroController libroController;
    private AutorDAO autorDAO;
    private RegistrarAutorView registrarAutorView;
    private AutorController autorController;
    private EliminarLibroView eliminarLibroView;
    private ListarLibroView listarLibroView;
    private ActualizarLibroView actualizarLibroView;
    private BuscarAutorView buscarAutorView;
    private EliminarAutorView eliminarAutorView;
    private ActualizarAutorView actualizarAutorView;
    private ListarAutorView listarAutorView;
    private RegistrarUsuarioView registrarUsuarioView;
    private UsuarioDAO usuarioDAO;
    private UsuarioController usuarioController;
    private BuscarUsuarioView buscarUsuarioView;
    private EliminarUsuarioView eliminarUsuarioView;
    private ActualizarUsuarioView actualizarUsuarioView;
    private ListarUsuarioView listarUsuarioView;
    /**
     * Creates new form PrinicipalView
     */
    public PrinicipalView() {
        initComponents();
        registrarLibroView = new RegistrarLibroView();
        buscarLibroView = new BuscarLibroView();
        libroDAO = new LibroDAOMemoria();
        autorDAO = new AutorDAOMemoria();
        registrarAutorView = new RegistrarAutorView();
        eliminarLibroView = new EliminarLibroView();
        listarLibroView= new ListarLibroView();
        actualizarLibroView = new ActualizarLibroView();
        buscarAutorView = new BuscarAutorView();
        eliminarAutorView = new EliminarAutorView();
        actualizarAutorView = new ActualizarAutorView();
        listarAutorView = new ListarAutorView();
        
        usuarioDAO = new UsuarioDAOMemoria();
        registrarUsuarioView = new RegistrarUsuarioView();
        buscarUsuarioView= new BuscarUsuarioView();
        eliminarUsuarioView = new EliminarUsuarioView();
        actualizarUsuarioView = new ActualizarUsuarioView();
        listarUsuarioView = new ListarUsuarioView();
        libroController = new LibroController(libroDAO,registrarLibroView,autorDAO,buscarLibroView, eliminarLibroView,listarLibroView,actualizarLibroView);
        autorController = new AutorController(autorDAO,registrarAutorView ,buscarAutorView,eliminarAutorView,actualizarAutorView,listarAutorView);
        usuarioController = new UsuarioController(usuarioDAO,registrarUsuarioView,buscarUsuarioView,eliminarUsuarioView,actualizarUsuarioView,listarUsuarioView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Libros");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Registrar");
        openMenuItem.addActionListener(this::openMenuItemActionPerformed);
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Buscar");
        saveMenuItem.addActionListener(this::saveMenuItemActionPerformed);
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Actualizar");
        saveAsMenuItem.addActionListener(this::saveAsMenuItemActionPerformed);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Eliminar");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        fileMenu.add(exitMenuItem);

        jMenuItem1.setText("Listar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        fileMenu.add(jMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Autor");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Registrar");
        cutMenuItem.addActionListener(this::cutMenuItemActionPerformed);
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Buscar");
        copyMenuItem.addActionListener(this::copyMenuItemActionPerformed);
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Eliminar");
        pasteMenuItem.addActionListener(this::pasteMenuItemActionPerformed);
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Actualizar");
        deleteMenuItem.addActionListener(this::deleteMenuItemActionPerformed);
        editMenu.add(deleteMenuItem);

        jMenuItem2.setText("Listar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        editMenu.add(jMenuItem2);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Usuario");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Registrar");
        contentMenuItem.addActionListener(this::contentMenuItemActionPerformed);
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Buscar");
        aboutMenuItem.addActionListener(this::aboutMenuItemActionPerformed);
        helpMenu.add(aboutMenuItem);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        helpMenu.add(jMenuItem3);

        jMenuItem4.setText("Actualizar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        helpMenu.add(jMenuItem4);

        jMenuItem5.setText("Listar");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        helpMenu.add(jMenuItem5);

        menuBar.add(helpMenu);

        jMenu1.setText("Prestamo");
        menuBar.add(jMenu1);

        jMenu2.setText("Devolucion");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
             if(!eliminarLibroView.isVisible()){ 
                    //libroController.cargarAutores();
                    desktopPane.remove(eliminarLibroView);
                    eliminarLibroView.setVisible(true);
                    desktopPane.add(eliminarLibroView);            
        } 
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
               if(!registrarLibroView.isVisible()){ 
                    libroController.cargarAutores();
                    registrarLibroView.setVisible(true);
                   desktopPane.remove(registrarLibroView);
                    
                    desktopPane.add(registrarLibroView);            
        } 
    // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
             if(!registrarAutorView.isVisible()){    
                    desktopPane.remove(registrarAutorView);
                    registrarAutorView.setVisible(true);
                    desktopPane.add(registrarAutorView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
                 if(!actualizarLibroView.isVisible()){    
                    desktopPane.remove(actualizarLibroView);
                    actualizarLibroView.setVisible(true);
                    desktopPane.add(actualizarLibroView);            
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
              if(!buscarLibroView.isVisible()){ 
                    //libroController.cargarAutores();
                    desktopPane.remove(buscarLibroView);
                    buscarLibroView.setVisible(true);
                    desktopPane.add(buscarLibroView);            
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                 if(!listarLibroView.isVisible()){ 
                    desktopPane.remove(listarLibroView);
                    listarLibroView.setVisible(true);
                    desktopPane.add(listarLibroView);            
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
                if(!buscarAutorView.isVisible()){    
                    desktopPane.remove(buscarAutorView);
                    buscarAutorView.setVisible(true);
                    desktopPane.add(buscarAutorView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
            if(!eliminarAutorView.isVisible()){    
                    desktopPane.remove(eliminarAutorView);
                    eliminarAutorView.setVisible(true);
                    desktopPane.add(eliminarAutorView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
              if(!actualizarAutorView.isVisible()){    
                    desktopPane.remove(actualizarAutorView);
                    actualizarAutorView.setVisible(true);
                    desktopPane.add(actualizarAutorView);            
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                 if(!listarAutorView.isVisible()){    
                    desktopPane.remove(listarAutorView);
                    listarAutorView.setVisible(true);
                    desktopPane.add(listarAutorView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
                if(!registrarUsuarioView.isVisible()){    
                    desktopPane.remove(registrarUsuarioView);
                    registrarUsuarioView.setVisible(true);
                    desktopPane.add(registrarUsuarioView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
              if(!buscarUsuarioView.isVisible()){    
                    desktopPane.remove(buscarUsuarioView);
                    buscarUsuarioView.setVisible(true);
                    desktopPane.add(buscarUsuarioView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
             if(!eliminarUsuarioView.isVisible()){ 
                    desktopPane.remove(eliminarUsuarioView);
                    eliminarUsuarioView.setVisible(true);
                    desktopPane.add(eliminarUsuarioView);            
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
                if(!actualizarUsuarioView.isVisible()){    
                    desktopPane.remove(actualizarUsuarioView);
                    actualizarUsuarioView.setVisible(true);
                    desktopPane.add(actualizarUsuarioView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
             if(!listarUsuarioView.isVisible()){    
                    desktopPane.remove(listarUsuarioView);
                    listarUsuarioView.setVisible(true);
                    desktopPane.add(listarUsuarioView);            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrinicipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrinicipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrinicipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrinicipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrinicipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
